#!/usr/bin/env python3
"""Emit only the reviewed representation metadata; never fetch or rebuild data."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POLICY = dict(transform="identity", equality="utf8-byte-exact", cardinality="zero-or-one",
              unmatched="exception", collision="ineligible")
CORE = "982916d73f0a35ff2558b0062f58aa3ac4f24d97"


def encoded(value):
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")


def pinned(path, expected):
    file = ROOT / path
    if file.is_symlink() or not file.is_file():
        raise ValueError(f"expected regular metadata file: {path}")
    data = file.read_bytes()
    if len(data) > 4 * 1024 * 1024 or hashlib.sha256(data).hexdigest() != expected:
        raise ValueError(f"reviewed metadata changed: {path}")
    return {"path": path, "sha256": expected}


def external(repository, revision, path, sha256):
    return dict(repository="https://github.com/" + repository, revision=revision,
                path=path, sha256=sha256)


def generate(check=False):
    document = build()
    data = encoded(document)
    envelope = encoded(dict(path="model/representations.json", sha256=hashlib.sha256(data).hexdigest()))
    for path, value in [("model/representations.json", data), ("source/representation-attachment.json", envelope)]:
        target = ROOT / path
        if check:
            if target.is_symlink() or not target.is_file() or target.read_bytes() != value:
                raise ValueError(f"generated metadata differs: {path}")
        else:
            if target.is_symlink():
                raise ValueError(f"refusing symbolic output: {path}")
            target.write_bytes(value)
    return document


def build():
    snapshot = pinned("source/artifact-snapshot.json", "b4ef99365a331865dfcb94c213995fe06dc1790f8054e3e7d96385af76c9179b")
    inputs = pinned("bridges/accepted-inputs.json", "513d5a7721afe73426df2412ea4a4e74d5914cb612ff80b9f0d7d3a0a679ce0d")
    accepted = json.loads((ROOT / inputs["path"]).read_bytes())
    target = dict(snapshot=snapshot, module="geonames", entity="geonames_countries",
                  property="iso", datatype="string", namespace="GeoNames:countryInfoISO2",
                  model=pinned("model/geonames.modelspec.json", "609fe73e07b84db65bdb1a904b9f84dd5c43bcbbc75eeb2d75f9a69ed3e8af81"),
                  keys=pinned("country-keys.json", "c57b21174d0f0d2badd575cf1c2605840bc862e6cebd52064ceffd9c266ee9c8"),
                  binding=dict(document=pinned("model/geonames.meaning.yaml", "21bb35aecf1f1214908f245cfeb2d0c5e7c6caf3915a5ffd604254642b3b4b57"),
                               concept="geonames-country", role="identifier",
                               meaning=dict(document=external("meaninggraph/core", CORE, "geo.meaning.yaml", "ee6eeea2e8038e016433a72dd15d45b6eaf89d3ae6e45893d4e5eeb7be61f4e9"), concept="country")))
    artifacts = {a["path"]: a for a in json.loads((ROOT / snapshot["path"]).read_bytes())["artifacts"]}
    contracts = []
    for item in accepted["bridges"]:
        table = item["table"]
        path = f"bridges/{table}.json"
        artifact = pinned(path, artifacts[path]["sha256"])
        export = json.loads((ROOT / path).read_bytes())
        if export != {"table": table, "rows": item["rows"]}:
            raise ValueError(f"export differs from reviewed accepted values: {table}")
        contracts.append(dict(execution="label-bridge", source=item["source"], target=target,
                              bridge=dict(artifact=artifact, table=table, raw_label_column="raw_label",
                                          target_key_column="target_key", serving_identity_column="serving_id"),
                              policy=POLICY, decision=item["decision"]))
    return dict(format="ovdb-representation-contract/2", contracts=contracts)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare generated bytes without writing")
    args = parser.parse_args()
    try:
        generate(args.check)
    except (ValueError, OSError, KeyError) as error:
        parser.exit(1, f"{error}\n")
    print("Representation metadata reproduced; semantic/canonical admission remains separate.")
